version: '3.8'

services:
  web:
    build: .
    ports:
      - "8002:8002"
    #volumes:
      #- ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1 
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: Dockerfile